### ISSUE TITLE
Help for setting Instagram keys in the project

### ISSUE THREAD

**Issue by ben55j** [ryder0064/instagram_basic_display_api#1]
Hello, 

Thank you for your package. I am having difficulties for setting the INSTAGRAM_CLIENT_ID and INSTAGRAM_CLIENT_SECRET to my project. 
Can you provide example files that could help ?
Also, is there any way I could set directly the keys to the project in order to make the process easier ?

Thank you for your help,
Benjamin

**Comment by ryder0064** [comment]
> Hello,
> 
> Thank you for your package. I am having difficulties for setting the INSTAGRAM_CLIENT_ID and INSTAGRAM_CLIENT_SECRET to my project. Can you provide example files that could help ? Also, is there any way I could set directly the keys to the project in order to make the process easier ?
> 
> Thank you for your help, Benjamin


d

**Comment by ryder0064** [comment]
> Hello,
> 
> Thank you for your package. I am having difficulties for setting the INSTAGRAM_CLIENT_ID and INSTAGRAM_CLIENT_SECRET to my project. Can you provide example files that could help ? Also, is there any way I could set directly the keys to the project in order to make the process easier ?
> 
> Thank you for your help, Benjamin

Hi @ben55j ,
You can refer to the [official website](https://developers.facebook.com/docs/instagram-basic-display-api/getting-started).
Just make sure you create your application and configure the Instagram Basic Display product. And there is the data you need inside the Instagram Basic Display on dashboard as attached.
![截圖 2022-02-17 下午3 10 05](https://user-images.githubusercontent.com/32318523/154424405-a350ece2-04d0-4aaf-b0b5-981e7e60774a.png)

Well, for simple data security, you need to add the keys for Android and iOS platform. So far this is the easiest way I can think of. 😅 
Hope that solves your problem.
Best regards, 
Ryder

**Comment by persadaditya** [comment]
I have difficulty too as you don't give a clear tutorial on where to locate it

in Android setting 
point number 1: do you mean the root directory of flutter or the root directory of android
point number 2: can you give some images so I can set it up better
point number 3: so is point number 2
